# ===============================
# APPLICATION
# ===============================
spring.application.name=measurementservice
server.port=8081

# ===============================
# EUREKA
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}

eureka.instance.non-secure-port=${server.port}
eureka.instance.home-page-url=http://127.0.0.1:${server.port}/
eureka.instance.status-page-url=http://127.0.0.1:${server.port}/actuator/info
eureka.instance.health-check-url=http://127.0.0.1:${server.port}/actuator/health

# ===============================
# MYSQL DATABASE (FIXED )
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/measurementdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# REDIS
# ===============================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ===============================
# DISABLE H2 (IMPORTANT )
# ===============================
spring.h2.console.enabled=false
# ===============================
# SWAGGER
# ===============================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
